### ISSUE TITLE
Formula checking being done against onekitch and restaurant driver message requests

### ISSUE THREAD

**Issue by Amosnomor** [HelpBerkeley/member-data#9]
I tested the latest version running the restaurant template formula checking, and found that it is running against onekitchen and restaurant driver requests and failing.

[test request](https://go.helpberkeley.org/t/request-onekitchen-driver-messages/4878/1680)

response:
Status: Failed
File: HBFreeDeliveries - 5_20_24ws-2.csv

Restaurant Template Error:
No Formula rows found within the Control Block. At least one valid Formula row is required.

The requirements:
- REQ-VRT-001-1 Validate formulas in OneKitchen Restaurant Template
- REQ-VRT-001-2 Validate formulas in regular Restaurant Template

Say that this should only be done on onekitchen and restaurant template requests.  Are the requirements wrong (which would seem to break backwards compatibility)?  Or is this a bug where we should only be doing the formula auditing on the onekitchen/restaurant template requests?

I've reverted the running image to the previous version.

**Comment by camdetaz** [comment]
It was a bug and we should only be doing formula auditing on onekitchen/restaurant template requests. 

This issue was fixed by: commit 69df6905a756c958e283842a97219445cc4571f5
